"""add user ownership to images and jobs

Revision ID: 0b2db96274e3
Revises: 5d13649bfea5
Create Date: 2026-09-18 08:56:14.132505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2db96274e3'
down_revision: Union[str, Sequence[str], None] = '5d13649bfea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_requests', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_image_requests_user_id'), 'image_requests', ['user_id'], unique=False)
    op.create_foreign_key('fk_image_requests_user_id_users', 'image_requests', 'users', ['user_id'], ['user_id'])
    op.add_column('jobs', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_foreign_key('fk_jobs_user_id_users', 'jobs', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "fk_jobs_user_id_users",
        "jobs",
        type_="foreignkey",
    )

    op.drop_index(
        op.f("ix_jobs_user_id"),
        table_name="jobs",
    )

    op.drop_column(
        "jobs",
        "user_id",
    )

    op.drop_constraint(
        "fk_image_requests_user_id_users",
        "image_requests",
        type_="foreignkey",
    )

    op.drop_index(
        op.f("ix_image_requests_user_id"),
        table_name="image_requests",
    )

    op.drop_column(
        "image_requests",
        "user_id",
    )
