"""add artifact model

Revision ID: 53dcc6141c85
Revises: 0b2db96274e3
Create Date: 2026-09-23 06:53:53.645423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53dcc6141c85'
down_revision: Union[str, Sequence[str], None] = '0b2db96274e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('storage_uri', sa.String(length=2048), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('parent_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['artifacts.artifact_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_index(op.f('ix_artifacts_media_type'), 'artifacts', ['media_type'], unique=False)
    op.create_index(op.f('ix_artifacts_parent_artifact_id'), 'artifacts', ['parent_artifact_id'], unique=False)
    op.create_index(op.f('ix_artifacts_user_id'), 'artifacts', ['user_id'], unique=False)
    op.add_column('image_requests', sa.Column('artifact_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_image_requests_artifact_id'), 'image_requests', ['artifact_id'], unique=False)
    op.create_foreign_key('fk_image_requests_artifact_id_artifacts', 'image_requests', 'artifacts', ['artifact_id'], ['artifact_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_image_requests_artifact_id_artifacts', 'image_requests', type_='foreignkey')
    op.drop_index(op.f('ix_image_requests_artifact_id'), table_name='image_requests')
    op.drop_column('image_requests', 'artifact_id')
    op.drop_index(op.f('ix_artifacts_user_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_parent_artifact_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_media_type'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
