"""support password authentication

Revision ID: 61d909272b05
Revises: c0cc7d4e5f83
Create Date: 2026-09-17 08:58:39.983697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '61d909272b05'
down_revision: Union[str, Sequence[str], None] = 'c0cc7d4e5f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.alter_column('users', 'google_sub',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'google_sub',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
