"""add tenant settings

Revision ID: 893c3d9ed3c7
Revises: c6de3d492a25
Create Date: 2026-10-09 12:31:07.263545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893c3d9ed3c7'
down_revision: Union[str, Sequence[str], None] = 'c6de3d492a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    connection = op.get_bind()

    connection.execute(
        sa.text(
            """
            INSERT INTO tenant_settings (
                tenant_id,
                allow_self_registration
            )
            SELECT
                tenant_id,
                false
            FROM tenants
            WHERE slug = 'default'
            """
        )
    )

    sa.Column('allow_self_registration', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_settings')
    # ### end Alembic commands ###
