"""add tenant ownership to executions

Revision ID: c6de3d492a25
Revises: 221a30e6bf4d
Create Date: 2026-10-08 17:26:11.796673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6de3d492a25'
down_revision: Union[str, Sequence[str], None] = '221a30e6bf4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('tenant_id', sa.String(length=36), nullable=True))

    # Instead of assuming every historical execution belongs to the default tenant, we can backfill the tenant_id based on the job's tenant_id.
    # This ensures that executions are correctly associated with their respective tenants.
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
            UPDATE executions
            SET tenant_id = jobs.tenant_id
            FROM jobs
            WHERE executions.job_id = jobs.job_id
                AND executions.tenant_id IS NULL
            """
        )
    )

    # Safety check
    missing_tenant_count = connection.execute(
        sa.text(
            """
            SELECT COUNT(*)
            FROM executions
            WHERE tenant_id IS NULL
            """
        )
    ).scalar_one()

    if missing_tenant_count:
        raise RuntimeError(
            f"{missing_tenant_count} executions "
            f"could not be assigned a tenant"
        )

    # 4. Enforce tenant ownership.
    op.alter_column(
        "executions",
        "tenant_id",
        existing_type=sa.String(length=36),
        nullable=False,
    )
    op.create_index(op.f('ix_executions_tenant_id'), 'executions', ['tenant_id'], unique=False)
    op.create_foreign_key("fk_executions_tenant_id_tenants", 'executions', 'tenants', ['tenant_id'], ['tenant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_constraint("fk_executions_tenant_id_tenants", 'executions', type_='foreignkey')
    op.drop_index(op.f('ix_executions_tenant_id'), table_name='executions')
    op.drop_column('executions', 'tenant_id')
    # ### end Alembic commands ###
