"""add tenancy foundation

Revision ID: e217d0603ccc
Revises: e8a66c6889c5
Create Date: 2026-10-08 12:59:53.450703

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e217d0603ccc'
down_revision: Union[str, Sequence[str], None] = 'e8a66c6889c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_table('tenant_domains',
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('hostname')
    )
    op.create_index(op.f('ix_tenant_domains_tenant_id'), 'tenant_domains', ['tenant_id'], unique=False)
    op.create_table('tenant_memberships',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id')
    )
    op.create_index(op.f('ix_tenant_memberships_role'), 'tenant_memberships', ['role'], unique=False)
    op.create_index(op.f('ix_tenant_memberships_status'), 'tenant_memberships', ['status'], unique=False)
    connection = op.get_bind()

    default_tenant_id = str(uuid.uuid4())

    # Add a default tenant and assign all existing users to it with the 'admin' role
    connection.execute(
        sa.text(
            """
            INSERT INTO tenants (
                tenant_id,
                slug,
                name,
                status,
                created_at
            )
            VALUES (
                :tenant_id,
                'default',
                'Default',
                'active',
                CURRENT_TIMESTAMP
            )
            """
        ),
        {
            "tenant_id": default_tenant_id,
        },
    )

    connection.execute(
        sa.text(
            """
            INSERT INTO tenant_memberships (
                tenant_id,
                user_id,
                role,
                status,
                created_at
            )
            SELECT
                :tenant_id,
                user_id,
                'admin',
                'active',
                CURRENT_TIMESTAMP
            FROM users
            """
        ),
        {
            "tenant_id": default_tenant_id,
        },
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_memberships_status'), table_name='tenant_memberships')
    op.drop_index(op.f('ix_tenant_memberships_role'), table_name='tenant_memberships')
    op.drop_table('tenant_memberships')
    op.drop_index(op.f('ix_tenant_domains_tenant_id'), table_name='tenant_domains')
    op.drop_table('tenant_domains')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
